# Generated by Django 5.1.5 on 2025-04-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Impressive title for the slide (e.g., 'Websites That Soar Above the Rest')", max_length=100)),
                ('bio', models.TextField(help_text='Short compelling bio/description for the slide', max_length=300)),
                ('image', models.ImageField(help_text='Upload an eye-catching image for this slide', upload_to='carousel/')),
                ('is_active', models.BooleanField(default=True, help_text='Should this slide be displayed?')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which slides appear (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carousel Slide',
                'verbose_name_plural': 'Carousel Slides',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
