# Generated by Django 5.1.5 on 2025-04-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='templates/thumbnails/')),
                ('preview_url', models.URLField(help_text='URL to the live preview (e.g., /templates/preview1/)')),
                ('download_url', models.URLField(help_text='Direct download link')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
