# Generated by Django 5.1.5 on 2025-04-08 14:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='description',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='projects',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='projects',
            name='preview_file',
            field=models.FileField(blank=True, help_text='Upload image or video if not using iframe.', null=True, upload_to='project_previews/'),
        ),
        migrations.AddField(
            model_name='projects',
            name='preview_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('iframe', 'iFrame')], default='image', max_length=10),
        ),
        migrations.AlterField(
            model_name='projects',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projects',
            name='download_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='projects',
            name='preview_url',
            field=models.URLField(blank=True, help_text="Use only if preview_type is 'iframe'.", null=True),
        ),
    ]
