# Generated by Django 5.1.5 on 2025-03-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team_members/', verbose_name='Image'),
        ),
    ]
