# Generated by Django 5.1.5 on 2025-02-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon_name',
            field=models.CharField(help_text="Class name of FontAwesome icon (e.g., 'fa fa-code')", max_length=50),
        ),
    ]
